version: '3.8'

services:
  db:
    image: postgres:17.4-alpine
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5444:5432"  # доступ к базе с хоста на порт 5444
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: on-failure
    ports:
      - "8888:8080" # проброс порта приложения
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    depends_on:
      - db
    volumes:
      - ./internal/db/migrations:/app/internal/db/migrations

volumes:
  postgres_data:
